#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INADECO_APLICACION_ESCRITORIO_WINDOWS_FORM
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="INADECO_GESTION")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertALUMNOS(ALUMNOS instance);
    partial void UpdateALUMNOS(ALUMNOS instance);
    partial void DeleteALUMNOS(ALUMNOS instance);
    partial void InsertPROFESORES(PROFESORES instance);
    partial void UpdatePROFESORES(PROFESORES instance);
    partial void DeletePROFESORES(PROFESORES instance);
    partial void InsertCURSOS(CURSOS instance);
    partial void UpdateCURSOS(CURSOS instance);
    partial void DeleteCURSOS(CURSOS instance);
    partial void InsertAULAS(AULAS instance);
    partial void UpdateAULAS(AULAS instance);
    partial void DeleteAULAS(AULAS instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::INADECO_APLICACION_ESCRITORIO_WINDOWS_FORM.Properties.Settings.Default.INADECO_GESTIONConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ALUMNOS> ALUMNOS
		{
			get
			{
				return this.GetTable<ALUMNOS>();
			}
		}
		
		public System.Data.Linq.Table<PROFESORES> PROFESORES
		{
			get
			{
				return this.GetTable<PROFESORES>();
			}
		}
		
		public System.Data.Linq.Table<CURSOS> CURSOS
		{
			get
			{
				return this.GetTable<CURSOS>();
			}
		}
		
		public System.Data.Linq.Table<AULAS> AULAS
		{
			get
			{
				return this.GetTable<AULAS>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ALUMNOS")]
	public partial class ALUMNOS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _DNI_ALUMNO;
		
		private string _NOMBRE;
		
		private string _PRIMER_APELLIDO;
		
		private string _SEGUNDO_APELLIDO;
		
		private string _DIRECCION;
		
		private string _CIUDAD;
		
		private System.Nullable<int> _CODIGO_POSTAL;
		
		private string _PROVINCIA;
		
		private string _TELEFONO;
		
		private string _EMAIL;
		
		private EntitySet<CURSOS> _CURSOS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDNI_ALUMNOChanging(string value);
    partial void OnDNI_ALUMNOChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    partial void OnPRIMER_APELLIDOChanging(string value);
    partial void OnPRIMER_APELLIDOChanged();
    partial void OnSEGUNDO_APELLIDOChanging(string value);
    partial void OnSEGUNDO_APELLIDOChanged();
    partial void OnDIRECCIONChanging(string value);
    partial void OnDIRECCIONChanged();
    partial void OnCIUDADChanging(string value);
    partial void OnCIUDADChanged();
    partial void OnCODIGO_POSTALChanging(System.Nullable<int> value);
    partial void OnCODIGO_POSTALChanged();
    partial void OnPROVINCIAChanging(string value);
    partial void OnPROVINCIAChanged();
    partial void OnTELEFONOChanging(string value);
    partial void OnTELEFONOChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    #endregion
		
		public ALUMNOS()
		{
			this._CURSOS = new EntitySet<CURSOS>(new Action<CURSOS>(this.attach_CURSOS), new Action<CURSOS>(this.detach_CURSOS));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNI_ALUMNO", DbType="NVarChar(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DNI_ALUMNO
		{
			get
			{
				return this._DNI_ALUMNO;
			}
			set
			{
				if ((this._DNI_ALUMNO != value))
				{
					this.OnDNI_ALUMNOChanging(value);
					this.SendPropertyChanging();
					this._DNI_ALUMNO = value;
					this.SendPropertyChanged("DNI_ALUMNO");
					this.OnDNI_ALUMNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(100)")]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this.OnNOMBREChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE = value;
					this.SendPropertyChanged("NOMBRE");
					this.OnNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRIMER_APELLIDO", DbType="NVarChar(100)")]
		public string PRIMER_APELLIDO
		{
			get
			{
				return this._PRIMER_APELLIDO;
			}
			set
			{
				if ((this._PRIMER_APELLIDO != value))
				{
					this.OnPRIMER_APELLIDOChanging(value);
					this.SendPropertyChanging();
					this._PRIMER_APELLIDO = value;
					this.SendPropertyChanged("PRIMER_APELLIDO");
					this.OnPRIMER_APELLIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEGUNDO_APELLIDO", DbType="NVarChar(100)")]
		public string SEGUNDO_APELLIDO
		{
			get
			{
				return this._SEGUNDO_APELLIDO;
			}
			set
			{
				if ((this._SEGUNDO_APELLIDO != value))
				{
					this.OnSEGUNDO_APELLIDOChanging(value);
					this.SendPropertyChanging();
					this._SEGUNDO_APELLIDO = value;
					this.SendPropertyChanged("SEGUNDO_APELLIDO");
					this.OnSEGUNDO_APELLIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRECCION", DbType="NVarChar(100)")]
		public string DIRECCION
		{
			get
			{
				return this._DIRECCION;
			}
			set
			{
				if ((this._DIRECCION != value))
				{
					this.OnDIRECCIONChanging(value);
					this.SendPropertyChanging();
					this._DIRECCION = value;
					this.SendPropertyChanged("DIRECCION");
					this.OnDIRECCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CIUDAD", DbType="NVarChar(100)")]
		public string CIUDAD
		{
			get
			{
				return this._CIUDAD;
			}
			set
			{
				if ((this._CIUDAD != value))
				{
					this.OnCIUDADChanging(value);
					this.SendPropertyChanging();
					this._CIUDAD = value;
					this.SendPropertyChanged("CIUDAD");
					this.OnCIUDADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_POSTAL", DbType="Int")]
		public System.Nullable<int> CODIGO_POSTAL
		{
			get
			{
				return this._CODIGO_POSTAL;
			}
			set
			{
				if ((this._CODIGO_POSTAL != value))
				{
					this.OnCODIGO_POSTALChanging(value);
					this.SendPropertyChanging();
					this._CODIGO_POSTAL = value;
					this.SendPropertyChanged("CODIGO_POSTAL");
					this.OnCODIGO_POSTALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROVINCIA", DbType="NVarChar(100)")]
		public string PROVINCIA
		{
			get
			{
				return this._PROVINCIA;
			}
			set
			{
				if ((this._PROVINCIA != value))
				{
					this.OnPROVINCIAChanging(value);
					this.SendPropertyChanging();
					this._PROVINCIA = value;
					this.SendPropertyChanged("PROVINCIA");
					this.OnPROVINCIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO", DbType="NVarChar(10)")]
		public string TELEFONO
		{
			get
			{
				return this._TELEFONO;
			}
			set
			{
				if ((this._TELEFONO != value))
				{
					this.OnTELEFONOChanging(value);
					this.SendPropertyChanging();
					this._TELEFONO = value;
					this.SendPropertyChanged("TELEFONO");
					this.OnTELEFONOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(100)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ALUMNOS_CURSOS", Storage="_CURSOS", ThisKey="DNI_ALUMNO", OtherKey="DNI_ALUMNO")]
		public EntitySet<CURSOS> CURSOS
		{
			get
			{
				return this._CURSOS;
			}
			set
			{
				this._CURSOS.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CURSOS(CURSOS entity)
		{
			this.SendPropertyChanging();
			entity.ALUMNOS = this;
		}
		
		private void detach_CURSOS(CURSOS entity)
		{
			this.SendPropertyChanging();
			entity.ALUMNOS = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PROFESORES")]
	public partial class PROFESORES : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _DNI_PROFESOR;
		
		private string _NOMBRE;
		
		private string _PRIMER_APELLIDO;
		
		private string _SEGUNDO_APELLIDO;
		
		private string _DIRECCION;
		
		private string _CIUDAD;
		
		private System.Nullable<int> _CODIGO_POSTAL;
		
		private string _PROVINCIA;
		
		private string _TELEFONO;
		
		private string _EMAIL;
		
		private EntitySet<CURSOS> _CURSOS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDNI_PROFESORChanging(string value);
    partial void OnDNI_PROFESORChanged();
    partial void OnNOMBREChanging(string value);
    partial void OnNOMBREChanged();
    partial void OnPRIMER_APELLIDOChanging(string value);
    partial void OnPRIMER_APELLIDOChanged();
    partial void OnSEGUNDO_APELLIDOChanging(string value);
    partial void OnSEGUNDO_APELLIDOChanged();
    partial void OnDIRECCIONChanging(string value);
    partial void OnDIRECCIONChanged();
    partial void OnCIUDADChanging(string value);
    partial void OnCIUDADChanged();
    partial void OnCODIGO_POSTALChanging(System.Nullable<int> value);
    partial void OnCODIGO_POSTALChanged();
    partial void OnPROVINCIAChanging(string value);
    partial void OnPROVINCIAChanged();
    partial void OnTELEFONOChanging(string value);
    partial void OnTELEFONOChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    #endregion
		
		public PROFESORES()
		{
			this._CURSOS = new EntitySet<CURSOS>(new Action<CURSOS>(this.attach_CURSOS), new Action<CURSOS>(this.detach_CURSOS));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNI_PROFESOR", DbType="NVarChar(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DNI_PROFESOR
		{
			get
			{
				return this._DNI_PROFESOR;
			}
			set
			{
				if ((this._DNI_PROFESOR != value))
				{
					this.OnDNI_PROFESORChanging(value);
					this.SendPropertyChanging();
					this._DNI_PROFESOR = value;
					this.SendPropertyChanged("DNI_PROFESOR");
					this.OnDNI_PROFESORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="NVarChar(100)")]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this.OnNOMBREChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE = value;
					this.SendPropertyChanged("NOMBRE");
					this.OnNOMBREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRIMER_APELLIDO", DbType="NVarChar(100)")]
		public string PRIMER_APELLIDO
		{
			get
			{
				return this._PRIMER_APELLIDO;
			}
			set
			{
				if ((this._PRIMER_APELLIDO != value))
				{
					this.OnPRIMER_APELLIDOChanging(value);
					this.SendPropertyChanging();
					this._PRIMER_APELLIDO = value;
					this.SendPropertyChanged("PRIMER_APELLIDO");
					this.OnPRIMER_APELLIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEGUNDO_APELLIDO", DbType="NVarChar(100)")]
		public string SEGUNDO_APELLIDO
		{
			get
			{
				return this._SEGUNDO_APELLIDO;
			}
			set
			{
				if ((this._SEGUNDO_APELLIDO != value))
				{
					this.OnSEGUNDO_APELLIDOChanging(value);
					this.SendPropertyChanging();
					this._SEGUNDO_APELLIDO = value;
					this.SendPropertyChanged("SEGUNDO_APELLIDO");
					this.OnSEGUNDO_APELLIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRECCION", DbType="NVarChar(100)")]
		public string DIRECCION
		{
			get
			{
				return this._DIRECCION;
			}
			set
			{
				if ((this._DIRECCION != value))
				{
					this.OnDIRECCIONChanging(value);
					this.SendPropertyChanging();
					this._DIRECCION = value;
					this.SendPropertyChanged("DIRECCION");
					this.OnDIRECCIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CIUDAD", DbType="NVarChar(100)")]
		public string CIUDAD
		{
			get
			{
				return this._CIUDAD;
			}
			set
			{
				if ((this._CIUDAD != value))
				{
					this.OnCIUDADChanging(value);
					this.SendPropertyChanging();
					this._CIUDAD = value;
					this.SendPropertyChanged("CIUDAD");
					this.OnCIUDADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_POSTAL", DbType="Int")]
		public System.Nullable<int> CODIGO_POSTAL
		{
			get
			{
				return this._CODIGO_POSTAL;
			}
			set
			{
				if ((this._CODIGO_POSTAL != value))
				{
					this.OnCODIGO_POSTALChanging(value);
					this.SendPropertyChanging();
					this._CODIGO_POSTAL = value;
					this.SendPropertyChanged("CODIGO_POSTAL");
					this.OnCODIGO_POSTALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROVINCIA", DbType="NVarChar(100)")]
		public string PROVINCIA
		{
			get
			{
				return this._PROVINCIA;
			}
			set
			{
				if ((this._PROVINCIA != value))
				{
					this.OnPROVINCIAChanging(value);
					this.SendPropertyChanging();
					this._PROVINCIA = value;
					this.SendPropertyChanged("PROVINCIA");
					this.OnPROVINCIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO", DbType="NVarChar(10)")]
		public string TELEFONO
		{
			get
			{
				return this._TELEFONO;
			}
			set
			{
				if ((this._TELEFONO != value))
				{
					this.OnTELEFONOChanging(value);
					this.SendPropertyChanging();
					this._TELEFONO = value;
					this.SendPropertyChanged("TELEFONO");
					this.OnTELEFONOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(100)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PROFESORES_CURSOS", Storage="_CURSOS", ThisKey="DNI_PROFESOR", OtherKey="DNI_PROFESOR")]
		public EntitySet<CURSOS> CURSOS
		{
			get
			{
				return this._CURSOS;
			}
			set
			{
				this._CURSOS.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CURSOS(CURSOS entity)
		{
			this.SendPropertyChanging();
			entity.PROFESORES = this;
		}
		
		private void detach_CURSOS(CURSOS entity)
		{
			this.SendPropertyChanging();
			entity.PROFESORES = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CURSOS")]
	public partial class CURSOS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_CURSO;
		
		private string _NOMBRE_CURSO;
		
		private System.Nullable<System.DateTime> _FECHA_INICIO;
		
		private System.Nullable<System.DateTime> _FECHA_FINALIZACION;
		
		private string _HORARIO;
		
		private string _DNI_ALUMNO;
		
		private string _DNI_PROFESOR;
		
		private System.Nullable<int> _ID_AULA;
		
		private EntityRef<ALUMNOS> _ALUMNOS;
		
		private EntityRef<PROFESORES> _PROFESORES;
		
		private EntityRef<AULAS> _AULAS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_CURSOChanging(string value);
    partial void OnID_CURSOChanged();
    partial void OnNOMBRE_CURSOChanging(string value);
    partial void OnNOMBRE_CURSOChanged();
    partial void OnFECHA_INICIOChanging(System.Nullable<System.DateTime> value);
    partial void OnFECHA_INICIOChanged();
    partial void OnFECHA_FINALIZACIONChanging(System.Nullable<System.DateTime> value);
    partial void OnFECHA_FINALIZACIONChanged();
    partial void OnHORARIOChanging(string value);
    partial void OnHORARIOChanged();
    partial void OnDNI_ALUMNOChanging(string value);
    partial void OnDNI_ALUMNOChanged();
    partial void OnDNI_PROFESORChanging(string value);
    partial void OnDNI_PROFESORChanged();
    partial void OnID_AULAChanging(System.Nullable<int> value);
    partial void OnID_AULAChanged();
    #endregion
		
		public CURSOS()
		{
			this._ALUMNOS = default(EntityRef<ALUMNOS>);
			this._PROFESORES = default(EntityRef<PROFESORES>);
			this._AULAS = default(EntityRef<AULAS>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CURSO", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_CURSO
		{
			get
			{
				return this._ID_CURSO;
			}
			set
			{
				if ((this._ID_CURSO != value))
				{
					this.OnID_CURSOChanging(value);
					this.SendPropertyChanging();
					this._ID_CURSO = value;
					this.SendPropertyChanged("ID_CURSO");
					this.OnID_CURSOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_CURSO", DbType="NVarChar(100)")]
		public string NOMBRE_CURSO
		{
			get
			{
				return this._NOMBRE_CURSO;
			}
			set
			{
				if ((this._NOMBRE_CURSO != value))
				{
					this.OnNOMBRE_CURSOChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE_CURSO = value;
					this.SendPropertyChanged("NOMBRE_CURSO");
					this.OnNOMBRE_CURSOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_INICIO", DbType="Date")]
		public System.Nullable<System.DateTime> FECHA_INICIO
		{
			get
			{
				return this._FECHA_INICIO;
			}
			set
			{
				if ((this._FECHA_INICIO != value))
				{
					this.OnFECHA_INICIOChanging(value);
					this.SendPropertyChanging();
					this._FECHA_INICIO = value;
					this.SendPropertyChanged("FECHA_INICIO");
					this.OnFECHA_INICIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_FINALIZACION", DbType="Date")]
		public System.Nullable<System.DateTime> FECHA_FINALIZACION
		{
			get
			{
				return this._FECHA_FINALIZACION;
			}
			set
			{
				if ((this._FECHA_FINALIZACION != value))
				{
					this.OnFECHA_FINALIZACIONChanging(value);
					this.SendPropertyChanging();
					this._FECHA_FINALIZACION = value;
					this.SendPropertyChanged("FECHA_FINALIZACION");
					this.OnFECHA_FINALIZACIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HORARIO", DbType="NVarChar(100)")]
		public string HORARIO
		{
			get
			{
				return this._HORARIO;
			}
			set
			{
				if ((this._HORARIO != value))
				{
					this.OnHORARIOChanging(value);
					this.SendPropertyChanging();
					this._HORARIO = value;
					this.SendPropertyChanged("HORARIO");
					this.OnHORARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNI_ALUMNO", DbType="NVarChar(9)")]
		public string DNI_ALUMNO
		{
			get
			{
				return this._DNI_ALUMNO;
			}
			set
			{
				if ((this._DNI_ALUMNO != value))
				{
					if (this._ALUMNOS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDNI_ALUMNOChanging(value);
					this.SendPropertyChanging();
					this._DNI_ALUMNO = value;
					this.SendPropertyChanged("DNI_ALUMNO");
					this.OnDNI_ALUMNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNI_PROFESOR", DbType="NVarChar(9)")]
		public string DNI_PROFESOR
		{
			get
			{
				return this._DNI_PROFESOR;
			}
			set
			{
				if ((this._DNI_PROFESOR != value))
				{
					if (this._PROFESORES.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDNI_PROFESORChanging(value);
					this.SendPropertyChanging();
					this._DNI_PROFESOR = value;
					this.SendPropertyChanged("DNI_PROFESOR");
					this.OnDNI_PROFESORChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_AULA", DbType="Int")]
		public System.Nullable<int> ID_AULA
		{
			get
			{
				return this._ID_AULA;
			}
			set
			{
				if ((this._ID_AULA != value))
				{
					if (this._AULAS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_AULAChanging(value);
					this.SendPropertyChanging();
					this._ID_AULA = value;
					this.SendPropertyChanged("ID_AULA");
					this.OnID_AULAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ALUMNOS_CURSOS", Storage="_ALUMNOS", ThisKey="DNI_ALUMNO", OtherKey="DNI_ALUMNO", IsForeignKey=true, DeleteRule="CASCADE")]
		public ALUMNOS ALUMNOS
		{
			get
			{
				return this._ALUMNOS.Entity;
			}
			set
			{
				ALUMNOS previousValue = this._ALUMNOS.Entity;
				if (((previousValue != value) 
							|| (this._ALUMNOS.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ALUMNOS.Entity = null;
						previousValue.CURSOS.Remove(this);
					}
					this._ALUMNOS.Entity = value;
					if ((value != null))
					{
						value.CURSOS.Add(this);
						this._DNI_ALUMNO = value.DNI_ALUMNO;
					}
					else
					{
						this._DNI_ALUMNO = default(string);
					}
					this.SendPropertyChanged("ALUMNOS");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PROFESORES_CURSOS", Storage="_PROFESORES", ThisKey="DNI_PROFESOR", OtherKey="DNI_PROFESOR", IsForeignKey=true, DeleteRule="CASCADE")]
		public PROFESORES PROFESORES
		{
			get
			{
				return this._PROFESORES.Entity;
			}
			set
			{
				PROFESORES previousValue = this._PROFESORES.Entity;
				if (((previousValue != value) 
							|| (this._PROFESORES.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PROFESORES.Entity = null;
						previousValue.CURSOS.Remove(this);
					}
					this._PROFESORES.Entity = value;
					if ((value != null))
					{
						value.CURSOS.Add(this);
						this._DNI_PROFESOR = value.DNI_PROFESOR;
					}
					else
					{
						this._DNI_PROFESOR = default(string);
					}
					this.SendPropertyChanged("PROFESORES");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AULAS_CURSOS", Storage="_AULAS", ThisKey="ID_AULA", OtherKey="ID_AULA", IsForeignKey=true, DeleteRule="CASCADE")]
		public AULAS AULAS
		{
			get
			{
				return this._AULAS.Entity;
			}
			set
			{
				AULAS previousValue = this._AULAS.Entity;
				if (((previousValue != value) 
							|| (this._AULAS.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AULAS.Entity = null;
						previousValue.CURSOS.Remove(this);
					}
					this._AULAS.Entity = value;
					if ((value != null))
					{
						value.CURSOS.Add(this);
						this._ID_AULA = value.ID_AULA;
					}
					else
					{
						this._ID_AULA = default(Nullable<int>);
					}
					this.SendPropertyChanged("AULAS");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AULAS")]
	public partial class AULAS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_AULA;
		
		private string _NOMBRE_AULA;
		
		private EntitySet<CURSOS> _CURSOS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_AULAChanging(int value);
    partial void OnID_AULAChanged();
    partial void OnNOMBRE_AULAChanging(string value);
    partial void OnNOMBRE_AULAChanged();
    #endregion
		
		public AULAS()
		{
			this._CURSOS = new EntitySet<CURSOS>(new Action<CURSOS>(this.attach_CURSOS), new Action<CURSOS>(this.detach_CURSOS));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_AULA", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_AULA
		{
			get
			{
				return this._ID_AULA;
			}
			set
			{
				if ((this._ID_AULA != value))
				{
					this.OnID_AULAChanging(value);
					this.SendPropertyChanging();
					this._ID_AULA = value;
					this.SendPropertyChanged("ID_AULA");
					this.OnID_AULAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_AULA", DbType="NVarChar(10)")]
		public string NOMBRE_AULA
		{
			get
			{
				return this._NOMBRE_AULA;
			}
			set
			{
				if ((this._NOMBRE_AULA != value))
				{
					this.OnNOMBRE_AULAChanging(value);
					this.SendPropertyChanging();
					this._NOMBRE_AULA = value;
					this.SendPropertyChanged("NOMBRE_AULA");
					this.OnNOMBRE_AULAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AULAS_CURSOS", Storage="_CURSOS", ThisKey="ID_AULA", OtherKey="ID_AULA")]
		public EntitySet<CURSOS> CURSOS
		{
			get
			{
				return this._CURSOS;
			}
			set
			{
				this._CURSOS.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CURSOS(CURSOS entity)
		{
			this.SendPropertyChanging();
			entity.AULAS = this;
		}
		
		private void detach_CURSOS(CURSOS entity)
		{
			this.SendPropertyChanging();
			entity.AULAS = null;
		}
	}
}
#pragma warning restore 1591
