<?xml version="1.0" encoding="utf-8"?><Database Name="INADECO_GESTION" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-ABUTR330\SQLEXPRESSJORGE;Initial Catalog=INADECO_GESTION;Persist Security Info=True;User ID=sa" SettingsObjectName="INADECO_APLICACION_ESCRITORIO_WINDOWS_FORM.Properties.Settings" SettingsPropertyName="INADECO_GESTIONConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ALUMNOS" Member="ALUMNOS">
    <Type Name="ALUMNOS">
      <Column Name="DNI_ALUMNO" Type="System.String" DbType="NVarChar(9) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PRIMER_APELLIDO" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SEGUNDO_APELLIDO" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DIRECCION" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CIUDAD" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CODIGO_POSTAL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PROVINCIA" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TELEFONO" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="ALUMNOS_CURSOS" Member="CURSOS" ThisKey="DNI_ALUMNO" OtherKey="DNI_ALUMNO" Type="CURSOS" />
    </Type>
  </Table>
  <Table Name="dbo.PROFESORES" Member="PROFESORES">
    <Type Name="PROFESORES">
      <Column Name="DNI_PROFESOR" Type="System.String" DbType="NVarChar(9) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PRIMER_APELLIDO" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SEGUNDO_APELLIDO" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DIRECCION" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CIUDAD" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CODIGO_POSTAL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PROVINCIA" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TELEFONO" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="PROFESORES_CURSOS" Member="CURSOS" ThisKey="DNI_PROFESOR" OtherKey="DNI_PROFESOR" Type="CURSOS" />
    </Type>
  </Table>
  <Table Name="dbo.AULAS" Member="AULAS">
    <Type Name="AULAS">
      <Column Name="ID_AULA" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NOMBRE_AULA" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Association Name="AULAS_CURSOS" Member="CURSOS" ThisKey="ID_AULA" OtherKey="ID_AULA" Type="CURSOS" />
    </Type>
  </Table>
  <Table Name="dbo.CURSOS" Member="CURSOS">
    <Type Name="CURSOS">
      <Column Name="ID_CURSO" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NOMBRE_CURSO" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FECHA_INICIO" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FECHA_FINALIZACION" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="HORARIO" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DNI_ALUMNO" Type="System.String" DbType="NVarChar(9)" CanBeNull="true" />
      <Column Name="DNI_PROFESOR" Type="System.String" DbType="NVarChar(9)" CanBeNull="true" />
      <Column Name="ID_AULA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ALUMNOS_CURSOS" Member="ALUMNOS" ThisKey="DNI_ALUMNO" OtherKey="DNI_ALUMNO" Type="ALUMNOS" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="AULAS_CURSOS" Member="AULAS" ThisKey="ID_AULA" OtherKey="ID_AULA" Type="AULAS" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="PROFESORES_CURSOS" Member="PROFESORES" ThisKey="DNI_PROFESOR" OtherKey="DNI_PROFESOR" Type="PROFESORES" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Function Name="dbo.cargarGridTodosDatos" Method="cargarGridTodosDatos">
    <ElementType Name="cargarGridTodosDatosResult">
      <Column Name="ID_CURSO" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NOMBRE_CURSO" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FECHA_INICIO" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FECHA_FINALIZACION" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="HORARIO" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DNI_ALUMNO" Type="System.String" DbType="NVarChar(9)" CanBeNull="true" />
      <Column Name="DNI_PROFESOR" Type="System.String" DbType="NVarChar(9)" CanBeNull="true" />
      <Column Name="ID_AULA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DNI_ALUMNO1" Type="System.String" DbType="NVarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="NOMBRE" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PRIMER_APELLIDO" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SEGUNDO_APELLIDO" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DIRECCION" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CIUDAD" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CODIGO_POSTAL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PROVINCIA" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TELEFONO" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DNI_PROFESOR1" Type="System.String" DbType="NVarChar(9) NOT NULL" CanBeNull="false" />
      <Column Name="NOMBRE1" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PRIMER_APELLIDO1" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SEGUNDO_APELLIDO1" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DIRECCION1" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CIUDAD1" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CODIGO_POSTAL1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PROVINCIA1" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TELEFONO1" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="EMAIL1" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ID_AULA1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NOMBRE_AULA" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CARGARGRIDCURSOS" Method="CARGARGRIDCURSOS">
    <ElementType Name="CARGARGRIDCURSOSResult">
      <Column Name="ID_CURSO" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NOMBRE_CURSO" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FECHA_INICIO" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FECHA_FINALIZACION" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="HORARIO" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DNI_ALUMNO" Type="System.String" DbType="NVarChar(9)" CanBeNull="true" />
      <Column Name="DNI_PROFESOR" Type="System.String" DbType="NVarChar(9)" CanBeNull="true" />
      <Column Name="ID_AULA" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.BuscarCurso" Method="BuscarCurso">
    <Parameter Name="ID_CURSO" Parameter="iD_CURSO" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="BuscarCursoResult">
      <Column Name="ID_CURSO" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NOMBRE_CURSO" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FECHA_INICIO" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FECHA_FINALIZACION" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="HORARIO" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DNI_ALUMNO" Type="System.String" DbType="NVarChar(9)" CanBeNull="true" />
      <Column Name="DNI_PROFESOR" Type="System.String" DbType="NVarChar(9)" CanBeNull="true" />
      <Column Name="ID_AULA" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>